package nornicdb

import (
	"context"
	"testing"
	"time"

	"github.com/orneryd/nornicdb/pkg/embed"
	"github.com/orneryd/nornicdb/pkg/inference"
	"github.com/orneryd/nornicdb/pkg/storage"
	"github.com/stretchr/testify/require"
)

type staticTestEmbedder struct {
	dims int
}

var _ embed.Embedder = (*staticTestEmbedder)(nil)

func (e *staticTestEmbedder) Embed(ctx context.Context, text string) ([]float32, error) {
	_ = ctx
	vec := make([]float32, e.dims)
	if len(vec) > 0 {
		vec[0] = float32(len(text))
	}
	if len(vec) > 1 {
		vec[1] = 1
	}
	return vec, nil
}

func (e *staticTestEmbedder) EmbedBatch(ctx context.Context, texts []string) ([][]float32, error) {
	_ = ctx
	out := make([][]float32, len(texts))
	for i, t := range texts {
		vec, _ := e.Embed(ctx, t)
		out[i] = vec
	}
	return out, nil
}

func (e *staticTestEmbedder) Dimensions() int { return e.dims }
func (e *staticTestEmbedder) Model() string   { return "static-test" }

func TestAutoTLP_ServerSideEmbeddingsTriggerInferenceOnEmbedded(t *testing.T) {
	ctx := context.Background()

	db, err := Open(t.TempDir(), nil)
	require.NoError(t, err)
	defer db.Close()

	// Keep the embed worker fast and deterministic in tests.
	db.embedWorkerConfig.BatchDelay = 0
	db.embedWorkerConfig.ScanInterval = time.Hour

	// Store two nodes WITHOUT embeddings. Auto-linking cannot run at Store() time.
	a, err := db.Store(ctx, &Memory{Content: "alpha"})
	require.NoError(t, err)
	b, err := db.Store(ctx, &Memory{Content: "beta"})
	require.NoError(t, err)

	edges, err := db.storage.AllEdges()
	require.NoError(t, err)
	require.Len(t, edges, 0)

	// Configure inference to always suggest B as similar to A.
	inferEngine, err := db.GetOrCreateInferenceService(db.defaultDatabaseName(), db.storage)
	require.NoError(t, err)
	require.NotNil(t, inferEngine)
	inferEngine.SetSimilaritySearch(func(ctx context.Context, embedding []float32, k int) ([]inference.SimilarityResult, error) {
		_ = ctx
		_ = embedding
		_ = k
		return []inference.SimilarityResult{{ID: b.ID, Score: 0.99}}, nil
	})

	// Enable server-side embeddings (async). When embeddings are persisted, the
	// embed worker's onEmbedded callback must also trigger inference.
	db.SetEmbedder(&staticTestEmbedder{dims: 3})

	require.Eventually(t, func() bool {
		out, err := db.storage.GetEdgesBetween(storage.NodeID(a.ID), storage.NodeID(b.ID))
		if err != nil {
			return false
		}
		for _, e := range out {
			if e != nil && e.AutoGenerated {
				return true
			}
		}
		return false
	}, 5*time.Second, 50*time.Millisecond)
}
